### ISSUE TITLE
Not Recognizing Disconnect, Nor Reconnecting

### ISSUE THREAD

**Issue by bendytree** [DyKnow/SignalR-ObjC#115]
I'm connecting to a PersistentConnection like this:

    self.con = [SRConnection connectionWithURL:@"http://10.0.1.24/MyCon/"];
    self.con.delegate = self;
    [self.con start];

When the connection happens, `SRConnectionDidOpen:` is called. Then, I can delete my website & even close down the virtual machine it is running on, but `SRConnectionDidClose:` is never called.

I even setup a poller to watch `self.con.state` but it always shows `connected` - even when it is disconnected. If I start the server again, the connection is never re-established.

Any ideas?

**Comment by abillingsley** [comment]
significant updates have been made to the SSE and Websockets transports.  This should be resolved now
