### ISSUE TITLE
Pluses becoming spaces in upstream string parameters

### ISSUE THREAD

**Issue by marcelocantos** [DyKnow/SignalR-ObjC#140]
I have found that string parameters with pluses in them have the pluses replaced by spaces. I stopped this by URL-encoding the postData values in the SRDefaultHttpHelper postInternal:… method. I'm guessing that this ought to be done since the data is posted as application/x-www-form-urlencoded.

Is this a bug in SignalR-ObjC (I can submit a pull request if you like) or am I doing something wrong?

**Comment by abillingsley** [comment]
SRDefaultHttpHelper has been removed in favor of AFNetworking
