### ISSUE TITLE
SinglaR 2.0

### ISSUE THREAD

**Issue by kallehiitola** [DyKnow/SignalR-ObjC#150]
I tried your client with SignalR 2.0 server that should support older protocol versions. It seems to work for some parts, but time to time I get and error saying: "The ConnectionId is in the incorrect format."

There is pretty good example of the error on Stackoverflow: http://stackoverflow.com/questions/18978904/signalr-server-error-the-connectionid-is-in-the-incorrect-format-with-signalr

Far as my investigation got me about the issue is that it has something to do with IPrincipal. See more here: https://github.com/SignalR/SignalR/issues/1589

**Comment by abillingsley** [comment]
this was resolved in the beta1 branch which is now in master
