### ISSUE TITLE
AFHTTPClient.h Missing in the AFNetworking (2.X)

### ISSUE THREAD

**Issue by katepanping** [DyKnow/SignalR-ObjC#153]
I integrated your project into mine, but when I just run it, I always got the error message 'AFHTTPClient.h' file not found in the 'SRDefaultHttpWebRequestWrapper.m' .

What should I do with this missing file?

**Comment by catordo** [comment]
AFHTTPClient is missing in 2.X of AFNetworking what is the replace file of this, I've still with the same problem

**Comment by 7934345** [comment]
+1 not woking, where is your update???

**Comment by rajeshaz09** [comment]
use New version 2.0.0.alpha1. It worked for me.
Podfile contents are

platform :ios, '8.0'
use_frameworks!

pod 'SignalR-ObjC', '2.0.0.alpha1'

xcodeproj 'objc/objc.xcodeproj'

**Comment by rajeshaz09** [comment]
Also look into this thread for latest updates 
https://github.com/DyKnow/SignalR-ObjC/issues/198

**Comment by 7934345** [comment]
yes! it works!

发自我的 iPod
