### ISSUE TITLE
Hub invoke completion block is calling twice

### ISSUE THREAD

**Issue by krin-san** [DyKnow/SignalR-ObjC#161]
Current commit: 694d0f7
Transport: SRWebSocketTransport

Using ```[hub invoke:withArgs:completionHandler:]``` this handler was called twice: once by SRWebSocketTransport **send** method, and once - by SRHubInvocation's callback block.

**Comment by sharmaharh** [comment]
This issue is occuring again in ios 9.3 to me in latest library of SignalR using cocoapods.

@echofool @abillingsley  please help me out.

**Comment by dhaval4gvm** [comment]
I also face same issue with this method. Can anyone have perfect solution  which don't mess other working flows.

**Comment by zhpengkun** [comment]
Same issue still exists.

**Comment by echofool** [comment]
Oops! I haven't used this in a long time.
