### ISSUE TITLE
Only first signal arrives on "Clients.OthersInGroup" signaling

### ISSUE THREAD

**Issue by jaiversin** [DyKnow/SignalR-ObjC#164]
I'm building a multi client app (web client and ObjC client) and I'm using groups to filter sessions. I have a Hub method for joining the group:

`Groups.Add(Context.ConnectionId, groupname);`

Then I'm using `Clients.OthersInGroup(groupname).signal(data);` on my server side to send the signals to the others members of the group.

For the ObjC Client, I'm using `pod 'SignalR-ObjC'` and I'm joining a group on the `- (void)SRConnectionDidOpen:(SRConnection *)connection` delegate method. The join group signal is OK.

The first signal I send from the Web client to the group, arrives perfectly to the iOS Client, but the next signals sent from the Web client are not being received at the iOS Client. (Sorry for being so redundant). 

In the other hand, all the signals sent from the iOS client are being received from the Web client.

UPDATE:
After the first signal received from the iOS Client, I keep getting a LongPolling log on the console every 2 seconds (According to the docs, it's due to a timeout):

`2014-03-21 12:04:19.594 SignalR.Samples.iOS[1186:60b] Thread <NSThread: 0x16e357e0>{name = (null), num = 1}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke79 [Line 157]
[LONG_POLLING]    will poll again in 2 seconds`

**Comment by andrewangtaylor** [comment]
I've got similar problem here. 
2015-02-16 09:13:09.225 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:-[SRHubConnection createHubProxy:] [Line 90]
[CONNECTION]    will create proxy quotesHub
2015-02-16 09:13:09.226 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:-[SRConnection negotiate:] [Line 145]
[CONNECTION]    will negotiate
2015-02-16 09:13:09.378 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:__26-[SRConnection negotiate:]_block_invoke [Line 153]
[CONNECTION]    negotiation was successful NegotiationResponse: ConnectionId=f539af10-9d8e-4ae1-94e6-e6f3b959506d ConnectionToken=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAj7aAvp83K0eLymig4Ji2AQAAAAACAAAAAAAQZgAAAAEAACAAAADBplmQoFpGrkGkBDTAZ+Ha5TbNo0vth40pHfhHv4vPgwAAAAAOgAAAAAIAACAAAAABDsRJNvjBt4hrTnCPUUB8o3U8oSnC7H13zrWbSHPYbjAAAAB7WykUInadwtjYhMMNli1qBxD+NcsrPDyaMQfJtevfM+tZL+kKBm7X6pJgU+4av1JAAAAAz17+dMTKDakgzjvDdSCluzrCp1nsXFSVvP9Dwth6AU09kvAKThDZA6pRWKD1LVBJzBzuZks64dO+e0KAlR9lrQ== Url=/live/signalr/signalr ProtocolVersion=1.3.0.0 TryWebSockets=1
2015-02-16 09:13:09.510 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke [Line 115]
[LONG_POLLING]    LP Receive: {"C":"d-F194B7D3-ESg,0|ESl,22|ESm,1|ESn,0|ESo,0","G":"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAj7aAvp83K0eLymig4Ji2AQAAAAACAAAAAAAQZgAAAAEAACAAAABBTIHMielTJ4/wSVBazl2a6Ayv2EyPouw5PGYVMA4x/QAAAAAOgAAAAAIAACAAAAD5BHKa0mNKA6t4GXZHl9PuD/earrM9wb6oIjfyynsrZkAAAABzPNQsLF86QNNOd9MJZJat9f4pZAMbCt6uBzONn2vIAU55UufCvK4a0npiKpyq251N4Grbkkb+C4fDyNZjaKSRQAAAACmO2npD/woTHq3G1qVXahdaQ+o7NxjRQqxILM0qEmDxg/7uMJx7hTjKZsbYnGhtd6iy15mU2UviWp3JTLczLJk=","M":[{"H":"QuotesHub","M":"Update","A":[{"Time":1423857599,"Symbol":"SKC:AGI","Bid":163.5,"Ask":164.25}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059989,"Symbol":"SWCO:AGI","Bid":53.4,"Ask":53.51}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059983,"Symbol":"SBCO:AGI","Bid":61.27,"Ask":61.38}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059984,"Symbol":"HSI:AGI","Bid":24695.0,"Ask":24705.0}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059947,"Symbol":"KOSPI:AGI","Bid":250.38,"Ask":250.48}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059937,"Symbol":"NIKK:AGI","Bid":18031.0,"Ask":18041.0}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059971,"Symbol":"USDCHF_b","Bid":0.92953,"Ask":0.92959}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059944,"Symbol":"GBPUSD_b","Bid":1.5414,"Ask":1.54146}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059971,"Symbol":"EURUSD_b","Bid":1.14048,"Ask":1.14054}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059933,"Symbol":"USDJPY_b","Bid":118.577,"Ask":118.583}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059968,"Symbol":"NZDUSD_b","Bid":0.74961,"Ask":0.74967}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059979,"Symbol":"AUDUSD_b","Bid":0.77771,"Ask":0.77777}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059977,"Symbol":"USDCAD_b","Bid":1.24397,"Ask":1.24403}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059961,"Symbol":"EURGBP_b","Bid":0.73987,"Ask":0.73993}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059972,"Symbol":"EURJPY_b","Bid":135.241,"Ask":135.247}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059967,"Symbol":"GBPJPY_b","Bid":182.78,"Ask":182.786}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059971,"Symbol":"CHFJPY_b","Bid":127.567,"Ask":127.573}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059983,"Symbol":"EURCHF_b","Bid":1.06013,"Ask":1.06019}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059940,"Symbol":"AUDJPY_b","Bid":92.221,"Ask":92.229}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059985,"Symbol":"GBPCHF_b","Bid":1.4328,"Ask":1.43287}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059976,"Symbol":"GBPCAD_b","Bid":1.91756,"Ask":1.91764}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059977,"Symbol":"GBPAUD_b","Bid":1.98193,"Ask":1.98198}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059769,"Symbol":"USDCNH_b","Bid":6.24853,"Ask":6.24858}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059918,"Symbol":"XAUUSD_b","Bid":1231.54,"Ask":1232.14}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424052003,"Symbol":"XAUEUR_b","Bid":1077.9,"Ask":1078.4}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059875,"Symbol":"XAGUSD_b","Bid":17.32,"Ask":17.38}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1423871880,"Symbol":"XAGEUR_b","Bid":15.22,"Ask":15.27}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1423868402,"Symbol":"NDX","Bid":4383.99,"Ask":4384.08}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059968,"Symbol":"NQH","Bid":4376.46,"Ask":4376.55}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1424059968,"Symbol":"NQM","Bid":4371.46,"Ask":4371.55}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1423673496,"Symbol":"NQU","Bid":4272.21,"Ask":4272.3}]},{"H":"QuotesHub","M":"Update","A":[{"Time":1423672098,"Symbol":"NQZ","Bid":4260.21,"Ask":4260.3}]},{"H":"QuotesHub","M":"Update","A":[{"Time":0,"Symbol":"FTSE","Bid":0.0,"Ask":0.0}]},{"H":"QuotesHub","M":"Update","A":[{"Time":0,"Symbol":"DAX","Bid":0.0,"Ask":0.0}]}]}
2015-02-16 09:13:09.513 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:__73-[SRAutoTransport start:connectionData:transportIndex:completionHandler:]_block_invoke [Line 123]
[AUTO_TRANSPORT]    did set active transport
2015-02-16 09:13:09.646 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke [Line 115]
[LONG_POLLING]    LP Receive: {"C":"d-F194B7D3-ESg,0|ESl,22|ESm,2|ESn,0|ESo,0","S":1,"M":[]}
2015-02-16 09:15:01.636 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke [Line 115]
[LONG_POLLING]    LP Receive:            {"C":"d-F194B7D3-ESg,0|ESl,22|ESm,2|ESn,0","M":[]}
2015-02-16 09:16:51.806 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke [Line 115]
[LONG_POLLING]    LP Receive:           {"C":"d-F194B7D3-ESg,0|ESl,22|ESm,2|ESn,0","M":[]}
2015-02-16 09:18:41.973 BOP[7155:186646] Thread <NSThread: 0x7af4f970>{number = 1, name = main}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke [Line 115]


I'm a newbies here. Anyone can help me please?

**Comment by abillingsley** [comment]
Please try SignalR-ObjC 2.0.1
