### ISSUE TITLE
WebSocket is not invoking server method

### ISSUE THREAD

**Issue by coderzilla** [DyKnow/SignalR-ObjC#167]
I'd connected with longpulling and invoked methods from self-host cross domain server without any error. But because of my applications needs i have to use WebSocket. But when i tried to connect like: 

SRWebSocketTransport *transport = [[SRWebSocketTransport alloc] init];
[[SignalRManager connection] start:transport];

i establish connection and server can invoke client method but when i try invoke method from client to server the "Request failed:bad request(400)" error occur.

Cannot figure out why that's happening. 

Thanks for your advices.. 

Edit: I'm getting 'Not a valid web socket request' from server. I catched it at 
- (BOOL)validateResponse:(NSHTTPURLResponse *)response
                    data:(NSData *)data
                   error:(NSError * __autoreleasing *)error
function.

**Comment by shams-ahmed** [comment]
@coderzilla did you found a fix?

**Comment by coderzilla** [comment]
Yes, i found a solution from Stackoverflow. Here is the link
http://stackoverflow.com/questions/23990998/signalr-ios-client-web-socket-transport-cannot-invoke-the-method-from-server

But it may be a fix for older versions.

2015-04-21 19:01 GMT+03:00 Shams Ahmed <notifications@github.com>:

**Comment by shams-ahmed** [comment]
@coderzilla thanks!

**Comment by abillingsley** [comment]
this is resolved in the 2.x version of SignalR-ObjC
