### ISSUE TITLE
Infinite loop Issue 

### ISSUE THREAD

**Issue by xyj6989** [DyKnow/SignalR-ObjC#168]
This issue is [Infinite loop Issue in AFURLConnectionOperation](https://github.com/AFNetworking/AFNetworking/issues/2133).

**Comment by abillingsley** [comment]
significant changes have been made to the SSE and WS transports including adding support for new AFNetworking which resolved https://github.com/AFNetworking/AFNetworking/pull/2496.  if this still reproduces please provide logs or a minimal sample
