### ISSUE TITLE
cant handle sudden connectionloss

### ISSUE THREAD

**Issue by aiQon** [DyKnow/SignalR-ObjC#169]
Hi,
Im using SignalR-ObjC with version 2.0.0.alpha1.

I establish my connection in the app's delegate like this:

    self.connection = [SRHubConnection connectionWithURL:@"http://someapi"];
    [self.connection setDelegate:self];
    self.hub = [self.connection createHubProxy:@"someHub"];
    [self.connection start: [[SRWebSocketTransport alloc] init]];

    [self.hub invoke:@"Connect" withArgs:[NSArray array] completionHandler:^(id response) {
        NSString *str = (NSString *)response;
        NSLog(@"Got connect response %@",str);
    }];

This works.

However, when I deploy this to my test device and deactivate the wifi connection in the device settings (to "emulate" connection-loss). The log goes nuts with several hundred of these entries:

    [WEB_SOCKETS]    Websocket Failed With Error e813a22c-56ed-4089-95f3-    556605e4f926, Error Domain=kCFErrorDomainCFNetwork Code=2 "The operation couldn’t     be completed. (kCFErrorDomainCFNetwork error 2.)" UserInfo=0x170274fc0     {kCFGetAddrInfoFailureKey=8}
    2014-06-30 13:19:37:025 app[11403:60b] errorError     Domain=kCFErrorDomainCFNetwork Code=2 "The operation couldn’t be completed.     (kCFErrorDomainCFNetwork error 2.)" UserInfo=0x170274fc0    {kCFGetAddrInfoFailureKey=8}
    2014-06-30 13:19:37.025 app[11403:60b] Thread <NSThread: 0x178072f80>{name = (null), num = 1}:-[SRWebSocketTransport performConnect:reconnecting:] [Line 104]
    [WEB_SOCKETS]    WS: http://someapi/signalr/signalr/signalr/reconnect?transport=webSockets&connectionToken=p6ADPyLWCOzATY0ARPjjZkbc7KgRmzniRBplJFnHur%2BUA%2FN5uJkHJ%2BJtHayTNkSk6yideawDT1%2FvrZfws0jt5%2FIf2z4El6hd%2B3nyGWT3SEXL0%2BDA&messageId=d-3DB59E03-P%2C299%7CT%2C0%7CU%2C1%7CV%2C0&connectionData=%5B%7B%22Name%22%3A%someHub%22%7D%5D
    2014-06-30 13:19:37.028 app[11403:60b] Thread <NSThread: 0x178072f80>{name = (null), num = 1}:-[SRWebSocketTransport webSocket:didFailWithError:] [Line 144]

And then crashes my app.

When I debug this and step through SRWebSocketTransport line 144 and 104 slowly, it does not crash. I assume its some race condition. Need to dig deeper, but wanted to let you know that I experience this.

**Comment by abillingsley** [comment]
do you see improved behavior with 2.0.1?
