### ISSUE TITLE
2.0.0.alpha1 only uses SRLongPollingTransport

### ISSUE THREAD

**Issue by tumatauenga** [DyKnow/SignalR-ObjC#173]
I am looking into using this library for a project, so have pulled down the latest version via CocoaPods (`2.0.0.alpha1`).  I have it up and running, but it seems to only use `SRLongPollingTransport`.  When I uncomment `SRWebSocketTransport` and `SRServerSentEventsTransport` classes in `SRAutoTransport`, I see a crash.

This made me think that perhaps I was a little too "bleeding edge" and perhaps I should be using `1.0.RC1` instead, however that version is not compatible with AFNetworking 2.0 which we are using in our project.

Is there any plans to continue development on the 2.0.0 version of this library? Do you have any advice for getting this working with WebSockets and AFNetworking 2.0?

Sincerely,

Ben.

**Comment by ramit-rulz** [comment]
Did you hear any updates on this?

**Comment by tumatauenga** [comment]
No never heard anything back

**Comment by shams-ahmed** [comment]
was you able to get Web Socket Transport working?

**Comment by tumatauenga** [comment]
No, I ended up just using Long Polling which worked O.K enough for our needs.

**Comment by abillingsley** [comment]
this was resolved as part of the beta1 branch which is now in master

**Comment by tumatauenga** [comment]
Fantastic, thanks Alex. Would you be able to update the podspec file to point to the new 2.0.0 tag?

**Comment by abillingsley** [comment]
we are still working on some unit tests and fixes for some other issues but once those are stable cocoapods will be updated

**Comment by tumatauenga** [comment]
Awesome news. I'll try out the beta in the meantime. Thanks Alex.
