### ISSUE TITLE
Method [hub on] not working!

### ISSUE THREAD

**Issue by kenpi04** [DyKnow/SignalR-ObjC#174]
I using Signalr-ObjC for my project!
This working very good! 
but i have one issues

  _connection = [SRHubConnection connectionWithURL:url];
            [_connection addValue:@"aaa" forHTTPHeaderField:@"token"];
            _hub = [_connection createHubProxy:hubName];
          [_hub on:@"sendMessGroup" perform:self selector:@selector(reciveMes:)];
           // [_connection setDelegate:self];
            _connection.started=^{
                NSLog(@"HUBS OPEN");
                [_hub invoke:@"Join" withArgs:@[_macAddress] completionHandler:^(id response) {

```
            }];

        };
        [_connection start];
```

-(void)reciveMes:(id)mesages
{
    NSString_data=(NSString_)mesages;
    NSLog(data);
}
method reciveMes not run when recived data from sever!

**Comment by chandrasekarkesavan** [comment]
I am struggling with the same issue. can you please help me to figure this out?
