### ISSUE TITLE
"pod setup" command stuck

### ISSUE THREAD

**Issue by balabs** [DyKnow/SignalR-ObjC#175]
Hi,

When I tried to setup SignalRObjC project, i followed the instructions, and I saw that after "pod setup" command the whole process stopped. 

There is just an information
"Setting up CocoaPods master repo".

Since there is no other logs and information, I quitted the terminal several times. But every time I started it over, the scenario was same.

Then I found out, in Activity Monitor there is process called git-remote-http which was downloading package more that 150 MB large, and it seems to cause the frozen-like terminal situation. It means the process was downloading all the time, and it took more that 15 minutes.

After the 20-25 minutes it finished.

"Setup completed" was the state.

I found other people had similar issues.

**Comment by orkoden** [comment]
The issue might be the [broken specs repo](http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/) described on the cocoa pods blog.
