### ISSUE TITLE
Signalr & CORS

### ISSUE THREAD

**Issue by EMIN3M1986** [DyKnow/SignalR-ObjC#177]
Hi . 
I'm using signalr and jquery ajax  (that connect to a  Soap Webservice) in a page together .
When I enable CPRS  from web.config
```xml
 <httpProtocol>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*"/>
        <add name="Access-Control-Allow-Headers" value="Content-Type"/>
      </customHeaders>
    </httpProtocol>
```
 the webserice work well but signalr can't establish connection with this error :" Error: Error during negotiation request. " and when I comment these lines in web.config and enable CORS in Startup.cs the Signalr work fine but jquery ajax alert CORS have to be enable to connect . 
I want to connect from localhost to internet server . 
how can I do ?

**Comment by abillingsley** [comment]
At DyKnow we have been using SignalR-ObjC with a Server configured for CORs with success.  If you can provide more detail or a sample that would be appreciated
