### ISSUE TITLE
Compilation error...

### ISSUE THREAD

**Issue by snakelecaps** [DyKnow/SignalR-ObjC#179]
-dynamic not specified the following flags are invalid: -ObjC 
rror: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-SignalR.Client.iOS-AFNetworking
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-SignalR.Client.iOS-AFNetworking is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-SignalR.Client.iOS-SocketRocket
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-SignalR.Client.iOS-SocketRocket is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -licucore
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -licucore is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-SignalR.Client.iOS
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-SignalR.Client.iOS is not an object file (not allowed in a library)

i followed your instructions and Im having this when i changed $(OTHER_LDFLAGS) to $(inherited) flag....
I need your help please :-)

**Comment by wssantanu** [comment]
Hi gurupatel
I have already follow those steps whatever u mentation 
but i didn't get add source to podfile and comment (or fix) _cancelled in AFURLConnectionOperation.m to fix the semantic issue error
In the Build Settings, do not override "Other Linker Flags". If it is bold, select it and press backspace, it'd -ObjC which I cleared.
 I am geting  can't locate file for: -lPods-SignalR.Client.iOS and  -lPods-SignalR.Client.iOS is not an object file (not allowed in a library) these two error
Can u pls hep me

**Comment by gurupatel** [comment]
![pods signalr client ios debug](https://cloud.githubusercontent.com/assets/3120193/9491206/f6cc366e-4c0a-11e5-8927-0570a29a264e.png)
![otherlinkerflag](https://cloud.githubusercontent.com/assets/3120193/9491210/fbc7636e-4c0a-11e5-845a-2e25e34ea00b.png)
![comment_cancelled1](https://cloud.githubusercontent.com/assets/3120193/9491212/ff97bb10-4c0a-11e5-8efb-35f641b21a17.png)
![comment_cancelled2](https://cloud.githubusercontent.com/assets/3120193/9491213/ffd80706-4c0a-11e5-90e7-53bbd1e5f5b1.png)
![Uploading Comment_Cancelled3.png…]()

**Comment by gurupatel** [comment]
@wssantanu : - Please check the above screen shots & follow that screen shots, if still you are facing issue than let me know.

**Comment by wssantanu** [comment]
Thx gurupatel

This error has been fixed. Now this project. building successfully.

But now how would i implement, i didnt get,
can u pls help?
