### ISSUE TITLE
How to change Transportation type to SRLongPollingTransport

### ISSUE THREAD

**Issue by yesnoyes** [DyKnow/SignalR-ObjC#181]
How to change Transportation type from client. The library by default is using SRLongPollingTransport. How do i change it to SRServerSentEventsTransport from client end.

I found this code which is SRAutoTransport class, using SRLongPollingTransport as default.

- (instancetype)init {
    NSArray *transports = @[//[[SRWebSocketTransport alloc] init],
                            //[[SRLongPollingTransport alloc] init],
                            [[SRServerSentEventsTransport alloc] init]];
    return [self initWithTransports:[NSMutableArray arrayWithArray:transports]];
}

**Comment by abillingsley** [comment]
in a previous version we mistakenly disabled websockets and sse.  This has been resolved in the master branch.
