### ISSUE TITLE
Groups are not working?

### ISSUE THREAD

**Issue by SaseGacev** [DyKnow/SignalR-ObjC#184]
I've just tested and noticed that:

Clients.Group(groupName)  and  Clients.OthersInGroup(groupName) are not working? Any response on this? Having groups  is kind a crucial for having a chat platform.

**Comment by brphelps** [comment]
Is this still an issue? Did you move to a different library?

**Comment by abillingsley** [comment]
At DyKnow we have been using Groups with success in SignalR-ObjC please update to 2.0.1 if this still reproduces please provide more details
