### ISSUE TITLE
[SignalR-ObjectC] State of connection 's alway connected.

### ISSUE THREAD

**Issue by ddbien** [DyKnow/SignalR-ObjC#185]
Dear !

I integrated signlR- objectC, I have  a issue that 
I connected to signlR server, after I turn off wifi and waiting about 2 minute,I turn on wifi , and I debug code in Xcode, I see  state of connection 's alway connected although App disconnected to signalR server and cannot send or received  message from another user.This is error of send message function: 

 "Error Domain=com.SignalR-ObjC.SRHubProxy Code=0 "There was an error invoking Hub method 'chathub.SendPrivateMessage'." UserInfo=0x1907ac40 {NSLocalizedFailureReason=NSInternalInconsistencyException, NSLocalizedDescription=There was an error invoking Hub method 'chathub.SendPrivateMessage'.} "

Please help me.

Thanks,
Bien Do

**Comment by abillingsley** [comment]
this should be fixed in the 2.x version of SignalR-ObjC
