### ISSUE TITLE
turn off console logs

### ISSUE THREAD

**Issue by shams-ahmed** [DyKnow/SignalR-ObjC#189]
how do i turn off the console logs?

**Comment by cswelin** [comment]
```static int ddLogLevel = LOG_LEVEL_OFF;```

in SRLog.h

**Comment by shams-ahmed** [comment]
i ready using cocoa lumber jack for my app... whenever i use the above code i get a redefinition error... i would like to disable it for signal-r without having to modify the source code

**Comment by abillingsley** [comment]
2.0.1 now supports CocoaLumberjack via a subspec install with 

```
SignalR-ObjC/CocoaLumberjack
```

You should now be able to use CocoaLumberjack to control SignalR log output

**Comment by canpoyrazoglu** [comment]
Hey,

I've just installed the latest version and setting `static int ddLogLevel = LOG_LEVEL_OFF;` doesn't work anymore. I don't use CocoaLumberjack. How do I turn the log off? (I also don't think modifying a header of a library to adjust log level is a good idea anyway)

**Comment by ltlombardi** [comment]
I'm having the same problem. LOG_LEVEL_OFF doesn't work
Besides, I import the library via cocoa Pods, and work in a team, so we don't commit to our svn the libraries.

**Comment by ozzotto** [comment]
What I did is comment out lines 33-45 but after the define statements.
`#define SRLogError(frmt, ...)   //LOG_OBJC_MAYBE(LOG_ASYNC_ERROR,   LOG_LEVEL_DEF, LOG_FLAG_ERROR,   0, frmt, ##__VA_ARGS__)`
`#define SRLogWarn(frmt, ...)    //LOG_OBJC_MAYBE(LOG_ASYNC_WARN,    LOG_LEVEL_DEF, LOG_FLAG_WARN,    0, frmt, ##__VA_ARGS__)`
`#define SRLogInfo(frmt, ...)    //LOG_OBJC_MAYBE(LOG_ASYNC_INFO,    LOG_LEVEL_DEF, LOG_FLAG_INFO,    0, frmt, ##__VA_ARGS__)`
`#define SRLogDebug(frmt, ...)   //LOG_OBJC_MAYBE(LOG_ASYNC_DEBUG,   LOG_LEVEL_DEF, LOG_FLAG_DEBUG,   0, frmt, ##__VA_ARGS__)`
`#define SRLogVerbose(frmt, ...) //LOG_OBJC_MAYBE(LOG_ASYNC_VERBOSE, LOG_LEVEL_DEF, LOG_FLAG_VERBOSE, 0, frmt, ##__VA_ARGS__)`
`#else`
`#define SRLogError(frmt, ...)      //do{ NSLog((frmt), ##__VA_ARGS__); } while(0)`
`#define SRLogWarn(frmt, ...)       //do{ NSLog((frmt), ##__VA_ARGS__); } while(0)`
`#define SRLogInfo(frmt, ...)       //do{ NSLog((frmt), ##__VA_ARGS__); } while(0)`
`#define SRLogDebug(frmt, ...)      //do{ NSLog((frmt), ##__VA_ARGS__); } while(0)`
`#define SRLogVerbose(frmt, ...)    //do{ NSLog((frmt), ##__VA_ARGS__); } while(0)`
