### ISSUE TITLE
reconnecting and reconnected events never fired 

### ISSUE THREAD

**Issue by ramit-rulz** [DyKnow/SignalR-ObjC#190]
I am able to connect an iOS client to SignalR server and communicate messages. But, when the SignalR server is shut down, the following SRConnectionDelegate methods are not called in the client:
SRConnectionDidSlow - Called ok
SRConnectionWillReconnect - Not called
SRConnectionDidReconnect - Not called
SRConnectionDidClose - Not called
The client remains stuck in didSlow method and the transport connection is lost. I observed this issue with ServerSentEvents and have not tried with other protocols.
I am using the latest version to support SignalR 2.0 server.
SignalR-ObjC version 2.0.0.alpha1
iOS 8.1
SignalR 2
Is this an unfinished version? Does anyone else have this issue?

**Comment by shams-ahmed** [comment]
@ramit-rulz try using there callback approach: onReconnecting, onReconnected.

**Comment by ramit-rulz** [comment]
Thanks for the reply @shams-ahmed.
I tried the callback approach with the following code but it doesn't help. I get the same result as before:
```
    connection.connectionSlow = ^{
        [self setStatusText:@"SLOW" Color:[UIColor whiteColor] backgroundColor:[UIColor orangeColor]];
    };
    connection.reconnecting = ^{
        [self setStatusText:@"RECONNECTING" Color:[UIColor whiteColor] backgroundColor:[UIColor yellowColor]];
    };
    connection.reconnected = ^{
        [self setStatusText:@"RECONNECTED" Color:[UIColor whiteColor] backgroundColor:[UIColor greenColor]];
    };
    connection.closed = ^{
        [self setStatusText:@"DISCONNECTED" Color:[UIColor whiteColor] backgroundColor:[UIColor redColor]];
    };
```

Any other insights?

**Comment by ramit-rulz** [comment]
Some more observations: 
The above issue is observed in feature branch **2.0.0.beta1**.
In **2.0.0.alpha1** the reconnect event is fired but the only transport protocol used is Long Polling. I see other protocols are commented out in SRAutoTransport.m file. Are these not implemented in this version?
Can someone point me to the correct version that runs with SignalR 2.0 server, supports transport protocols other than long polling and handled reconnect and disconnect callbacks/delegate methods?

**Comment by JoseMendesGouveia** [comment]
I have the same issue. With a SignalR 2 server and SignalR-ObjC 2.0.0 alpha, the callbacks are not executed, with the exception of "connectionSlow", but there are entry logs such as:

- SRHeartbeatMonitor beat: Connection Timed-out: Transport Lost Connection
- SRAutoTransport lostConnection: lostConnection

I also tested the Long Polling Transport Protocol, it does detect the network failure, and attempt the reconnection but is less performant.

This issue has already been addressed, or there is some solution for it?

**Comment by akgulem** [comment]
Is there any fix for that?

**Comment by joeldart** [comment]
Pretty sure it's fixed. We put in a ton of effort on shoring up the reliability and adding unit tests around these particular error conditions in 2.0.0.beta3

**Comment by akgulem** [comment]
Thank you very much for your answer1 :)

**Comment by akgulem** [comment]
So, what's the ultimate way of installing the library? Using cocoapods, I run into this problem.

**Comment by joeldart** [comment]
What version does it say in your podfile?

**Comment by akgulem** [comment]
Oh God, I did not specify the version of it in my podfile since it is not written in the document below:
https://cocoapods.org/?q=signalr
However, when I clicked on installation guide, I saw. Could you also fix that please? 
Thank you very much :)

**Comment by akgulem** [comment]
I installed and used in my project. When I switched off the wifi, reconnecting callback worked whereas reconnected callback did not just after I switched on the wifi. Should not it be in the same function? What am I doing wrong?

**Comment by akgulem** [comment]
Hello @joeldart ,

I struggled with a lot with the library and my observations are:
-connection.received and connection.reconnecting work
-After switch off-switch on the WiFi,connection.reconnected does not work.

I just wanted to inform.
Thanks :)

**Comment by joeldart** [comment]
Does it go to the disconnected state? My understanding has been if you go to the disconnected state that you need to explicitly connect again. If there is a wifi switch off and then on again, it should transfer Connected -> Reconnecting -> Connected.

**Comment by akgulem** [comment]
The reason behind switching on and off is that anytime wifi connection can be lost and and at this point, it should  try to reconnect for a certain time. I also tried the hub connection and it worked when I switched off/on my wifi, not always did it work though.
