### ISSUE TITLE
Nothing specifically wrong - just need help

### ISSUE THREAD

**Issue by earlesja** [DyKnow/SignalR-ObjC#191]
Hi - I have been working on a project using 'SignalR-ObjC', but have yet to be able to get a working connection. Are the suggested code samples all that people have used? Is there a public server that I could use as a test to determine whether it is a problem with our server or not?

It's now obvious to me that this does work for people based on the recent issues posted, but I can't seem to figure out where I'm going wrong. The code 'connects' (I can tell via network traffic), but the status never changes beyond 'connecting'. My client receives constant long polls from the server, but again, never anything beyond that.

I can post my code snippets and logs tomorrow; I'm using mobile currently.

Thanks in advance, and I will update tomorrow.
-Jonathan

**Comment by earlesja** [comment]
My current code setup:

    func hubTest(){
        var con = SRHubConnection(URLString: "url")
        var proxy = con.createHubProxy("hubname") as SRHubProxy

        proxy.on("received method", perform: self, selector: "messageReceived")
        
        con.started = { () in
            proxy.invoke("join", withArgs: ["groupName"])
        }
        //con.delegate = self
        con.start()
    }

    func messageReceived(message : NSString) {
        NSLog("Obviously long message to verify functionality!")
        NSLog(message)
    }
    

My log output:
2015-04-13 11:59:08.230 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:-[SRHubConnection createHubProxy:] [Line 76]
[CONNECTION]    will create proxy MetricHub
2015-04-13 11:59:08.232 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:-[SRConnection negotiate:] [Line 138]
[CONNECTION]    will negotiate
2015-04-13 11:59:08.297 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:__26-[SRConnection negotiate:]_block_invoke [Line 146]
[CONNECTION]    negotiation was successful NegotiationResponse: ConnectionId=dc1f9751-73f0-4149-99e5-120a6bf9609d ConnectionToken=Dy3v8LaAxY62inNof8KTTbLD6H7ycHAj1bhrWSkn0MFOYBIlKvgHKTGMn1GMBWYzyQ2GbPoJznEOlaUSoS1MwyKagr3jkFUYQbWJYsqsfK4KRjg0ag9vtAaqH+XtCwJ8 Url=[Obfuscated] ProtocolVersion=1.3.0.0 TryWebSockets=0
2015-04-13 11:59:08.316 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke [Line 121]
[LONG_POLLING]    LP Receive: {"C":"d-65500170-A,0|Q,0|R,1|S,0","S":1,"M":[]}
2015-04-13 11:59:08.316 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:__73-[SRAutoTransport start:connectionData:transportIndex:completionHandler:]_block_invoke [Line 132]
[AUTO_TRANSPORT]    did set active transport
2015-04-13 11:59:08.317 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:-[SRAutoTransport send:data:connectionData:completionHandler:] [Line 146]
[AUTO_TRANSPORT]    will send data from active transport
2015-04-13 11:59:08.317 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:-[SRHttpBasedTransport send:data:connectionData:completionHandler:] [Line 122]
[HTTP_BASED_TRANSPORT]    will send data
2015-04-13 12:01:02.100 signal[954:23525] Thread <NSThread: 0x7fde7a70ab40>{number = 1, name = main}:__64-[SRLongPollingTransport poll:connectionData:completionHandler:]_block_invoke [Line 121]
[LONG_POLLING]    LP Receive:            {"C":"d-65500170-A,0|Q,0|R,1|S,0","M":[]}

And it will just continue long polling without any call to my local method. Maybe I'm missing something about how this is supposed to work, but this project is using SignalR as simply a data broadcast with devices listening to it - so that is all I'm attempting.

**Comment by ramit-rulz** [comment]
2 tips:
1. Uncomment con.delegate = self 
2. Add a colon after the func name in proxy.on() call - as selector: "messageReceived:"

**Comment by earlesja** [comment]
Thank you for the input - I just tried switching to utilize both of these changes, and I am still not receiving messages. I know the server is broadcasting, because we have a Javascript client setup that posts these simple messages to a webpage.

Any other thoughts?

**Comment by ramit-rulz** [comment]
This works for me in Objective-C:
```
- (void)viewDidLoad {
    [super viewDidLoad];
    connection = [SRHubConnection connectionWithURL:urlString];
    myHub = [connection createHubProxy:@"Hub"];
    [myHub on:@"addNewMessageToPage" perform:self selector:@selector(updatePageWithName:)];
    [connection setDelegate:self];
    [connection start];
}
- (void)updatePageWithName:(id)name {
    //do something with the message    
}
```
Try replacing the con.started callback with the delegate method SRConnectionDidOpen and see if that helps.

**Comment by earlesja** [comment]
I tried setting up a test project in ObjC as well - to no avail. I'm starting to bet something is wrong with our server configuration.

Just as a final thought: What version of SignalR-ObjC are you using?

If anyone else is curious, I get 6bytes worth of incoming data every ~10 seconds, and long polls every ~30 seconds or so. Nothing else. My status is connected, but nothing else ever comes through.

**Comment by krunalsheth** [comment]
@earlesja  did you figure out what the problem was. i am running into same issue.

**Comment by earlesja** [comment]
Nope - this was an incredibly disheartening experience.

**Comment by bherila** [comment]
I think the protocol implementation here is outdated, it would probably be better to try to use the official javascript jquery client somehow and wrap that in a thin iOS layer.
