### ISSUE TITLE
connect error when token with letter "+"

### ISSUE THREAD

**Issue by czcz1024** [DyKnow/SignalR-ObjC#193]
send "+" to server ,may get a space,so need to replay it to "%2b",
in SRHttpBasedTransport.m
receiveQueryString method and sendQueryString method
change it to :
NSString *token=[connection.connectionToken stringByAddingPercentEscapesUsingEncoding:NSASCIIStringEncoding];
token=[token stringByReplaceingOccurrencesOfString:@"+" withString:@"%2b"];

after use token

**Comment by abillingsley** [comment]
receiveQueryString and sendQueryString methods are no longer used.  AFNetworking now takes care of escaping these values.
