### ISSUE TITLE
How can it be used with Swift?

### ISSUE THREAD

**Issue by abinop** [DyKnow/SignalR-ObjC#195]
How would you call 

```
connection.received = ^(NSString * data) {
    NSLog(data);
};
connection.started =  ^{
    [connection send:@"hello world"];
};
```

using Swift?

**Comment by sjmadsen** [comment]
We're only just starting to look at this library, but something like this should work, once you add the necessary files to your bridging header:

    connection.received = { data in
        NSLog(data)
    }
    connection.started = {
        connection.send("hello world")
    }

**Comment by abinop** [comment]
This does not work I am afraid, it seems that a different type of syntax is needed...

**Comment by abinop** [comment]
I found it, I should initialize SRHubConnection, not SRConnection

**Comment by ergunkocak** [comment]
There is also a swift port : https://github.com/skerkewitz/SwignalR
