### ISSUE TITLE
Compilation error after adding it through cocoapod

### ISSUE THREAD

**Issue by krunalsheth** [DyKnow/SignalR-ObjC#197]
Hi,

Apoloogies in advance. I am very new to iOS and swift and Objective c development. 

I added the SignalR-objc through cocoapod to an brand new project. (created through 'single view application' template inside iOS->Application. and I am running into following errors. 

/Users/krunal/Documents/iOS/SampleC/Pods/SignalR-ObjC/SignalR.Client/Http/SRDefaultHttpWebRequestWrapper.m:23:9: 'AFHTTPClient.h' file not found
/Users/krunal/Documents/iOS/SampleC/Pods/AFNetworking/AFNetworking/AFURLConnectionOperation.h
/Users/krunal/Documents/iOS/SampleC/Pods/AFNetworking/AFNetworking/AFURLConnectionOperation.h:200:1: Property with 'retain (or strong)' attribute must be of object type
/Users/krunal/Documents/iOS/SampleC/Pods/AFNetworking/AFNetworking/AFURLConnectionOperation.h:209:1: Property with 'retain (or strong)' attribute must be of object type

Based on internet search it seems AFHTTPClient.h isn't there anymore for for AFNetworking.  anyone has solved this issue? which header file should be used instead?

My  Xcode version is 6.3.1(6D1002)

Thanks in advance.

**Comment by rajeshaz09** [comment]
use New version 2.0.0.alpha1. It worked for me.
Podfile contents are
-------------

platform :ios, '8.0'
use_frameworks!


pod 'SwiftR'

pod 'SignalR-ObjC', '2.0.0.alpha1'

xcodeproj 'objc/objc.xcodeproj'

**Comment by abinop** [comment]
'2.0.0.alpha1' no longer exists, what should we replace it with?
