### ISSUE TITLE
2 years since last check in

### ISSUE THREAD

**Issue by rajeshaz09** [DyKnow/SignalR-ObjC#198]
Does this project actively maintaining? 2 years since last checkin and 2.0.0 version is still in alpha stage. Please let me know, If you need my help.

**Comment by joeldart** [comment]
we've been using the feature-2.0.0.beta1 in prod on osx and ios for that whole time. I assume that you're noting the big change needs to be done in cocoapods to point to the correct working version?

**Comment by rajeshaz09** [comment]
I am evaluating SignalR for my product. 

cocoapods by default gets "1.0.1" version of code, which has issues with AFNetworking framework. I was under impression that, "2.0.0.alpha1" version is not stable. 
I have few questions
1) 2.0.0-beta1 means, are you referring to "2.0.0.alpha1" ( http://cocoadocs.org/docsets/SignalR-ObjC/2.0.0.alpha1/  ) ?
 2) Does current version support latest version of server? (SignalR 2.2.0  https://www.nuget.org/packages/Microsoft.AspNet.SignalR/2.2.0 ). SignalR team is planning to release version 3 soon.

**Comment by bherila** [comment]
Even with the latest cocoapods, I was not able to get this working with the latest version of SignalR.

**Comment by rajeshaz09** [comment]
I have strange problems with 2.0.0.alpha1
1) Client is always fallback to "Long polling" method
2) I created 2 sample clients using ObjectiveC and swift. ObjectiveC client is working as expected. But swift client is not working properly. Client can able to calls erver methods but server can't (No exception either)

Environment:
Server: SignalR 2.2.0 (.Net 4.6 using VS 2015)
Clients: swift, objectiveC using xCode 6.4
SignalR-ObjC version: 2.0.0.alpha1

**Comment by joeldart** [comment]
1. Yes our cocoa pods is horribly out of date. The 2.0 branch became latest
stable quickly. I can say against a 2.0.2 server the beta1 branch is good.
We have an internal pod that pointed up at edge so we could test before
bumping everyone. Then there was a change in the cocoa pods process and we
need to relearn how to deploy that.
2. There are reported bugs at this point. We haven't moved to that server
yet so don't have experience on that yet. Also were not aware of any solid
compliance/integration tests for clients

**Comment by joeldart** [comment]
okay, we have a development branch we never tagged which is why it never
showed up in cocoapods. I'll get that updated and THAT will be the
suggested version.
https://github.com/DyKnow/SignalR-ObjC/compare/2.0.0.alpha1...feature-2.0.0.beta1

Also have to get used to all the cocoapods tooling changes (for the better
I'm sure)

**Comment by rajeshaz09** [comment]
Thanks Joeldart...
Waiting for COCOAPODS release.

**Comment by JoseMendesGouveia** [comment]
Like Rajeshaz, I'm also evaluating SignalR-ObjC for an app.
I have already been testing Alpha, and most recently the Beta1 branches. Refering to the latest one (Beta1) I noticed the protocol fallback to "Long Polling" and also a network failure detection, through callback methods that should be called, when the connection to the server is lost, but in reality they are never called (SRConnectionWillReconnect, SRConnectionDidReconnect, SRConnectionDidClose).

Joel, there are any predictions in the near future for a release of a new version with those bugs corrected?

**Comment by rajeshaz09** [comment]
Beta1 is also not stable. Connection drop issues.  
As a backup plan, I created small library using WKWebView to load a URL from server which interacts with APP. This is working very good.

**Comment by joeldart** [comment]
Update on this: getting about 15 errors when trying to lint the spec file. Tracking all those down is the blocker

**Comment by JoseMendesGouveia** [comment]
Thanks for your contribution!
Rajeshaz, could you kindly share your small library?

Joel, thanks for the update! Do you predict a fast resolution of those errors?

**Comment by shams-ahmed** [comment]
try using our fork version of signal r....

its basically version 2 but with some changes to make it less crash and more stable

```
pod 'SignalR-ObjC', :git => 'https://github.com/SimplifydigitalLtd/SignalR-ObjC.git', :branch => 'feature-2.0.0.beta1' 
```

**Comment by JoseMendesGouveia** [comment]
Thank you Shams-Ahmed, 
I will give it a try, and post the feedback as soon as possible.

**Comment by JoseMendesGouveia** [comment]
I have tested your version, Shams-Ahmed.
It works, but doesn't solve the main issues of the framework: connection drop, connection recovery and protocol fallback.

**Comment by joeldart** [comment]
@JoseMendesGouveia I added a new beta1 and am looking into the connection drop/recovery. I believe it is solved for ServerSentEvents in latest ( SignalR-ObjC (2.0.0.beta1)
   Objective-C Client for the SignalR Project works with iOS and Mac.
   pod 'SignalR-ObjC', '~> 2.0.0.beta1'

I am working on WebSockets next with link conditioner but am wondering what cases you've observed

**Comment by JoseMendesGouveia** [comment]
Thank you Joel for your support.
I will update my xcode and test the new version.
I will give feedback as soon as possible.

**Comment by JoseMendesGouveia** [comment]
@joeldart Regarding the connection failure I have tested in ServerSentEvents and Long Polling protocols, in both cases I have tested in the simulator and not in a real device, and also for both I have turned off and on my iMac Wi-Fi connection. Regarding the WebSockets protocol I have not tested yet, because the SignalR server I'm using runs on IIS 7.5.

**Comment by JoseMendesGouveia** [comment]
@joeldart 
I have tested the most recent version (31-07-2015). I focused on the ServerSentEvent protocol, which is working successfully! It already detects the connection drop and the "closed", "reconnecting" and "stateChanged" callbacks are successfully called, when the connection drops.
The issue now relies on the connection recovery. When the connection with the server is restored no callback is called.

**Comment by backofthecup** [comment]
After upgrading from 2.0.0.alpha1 to 2.0.0.beta1, I'm getting a connection error using the new method:
SRHubConnection connectionWithURLString:queryString:

Here is the code:
````
NSDictionary *params = @{@"authToken" : @"someauthtoken", @"apiKey" : @"abd123"};
NSString *path = @"someURL";
[SRHubConnection connectionWithURLString:path queryString:params]
````


This worked fine with old method in 2.0.0.alpha1.

**Comment by JoseMendesGouveia** [comment]
@backofthecup 
I use the connectionWithURLString method too, and is working perfectly. Detail your connection error, so we can help you.

**Comment by backofthecup** [comment]
@JoseMendesGouveia 
I'm getting a 404 because the URL constructed when supplying a queryString is invalid. Another user created a specific issue for this problem.
Are you using a queryString argument? It works when this param is nil but not when populated. When populated the URL does not get constructed correctly thus getting a 404.

**Comment by JoseMendesGouveia** [comment]
@backofthecup 
I use successfully "queryString" parameter. 
From version alpha to beta, "queryString" changed from a NSString to NSDictionary. I believe your error resides in the construction of your NSDictionary. Example code:


NSArray *val = [[NSArray alloc] initWithObjects: someauthtoken, "abd123", nil];
NSArray *key = [[NSArray alloc] initWithObjects: @"authtoken", @"apiKey", nil];
NSDictionary *dict = [[NSDictionary alloc initWithObjects:val forKeys:key];
_authenticatedConnection = [SRHubConnection connectionWithURL:path queryString:dict];

**Comment by backofthecup** [comment]
@JoseMendesGouveia 
And what is wrong with constructing the dictionary this way:

````
NSDictionary *params = @{@"authToken" : @"someauthtoken", @"apiKey" : @"abd123"};

````

**Comment by JoseMendesGouveia** [comment]
It shouldn't be wrong, but I had errors with a dicitionary populated in a similar way. 
I'm just showing code that works!

**Comment by backofthecup** [comment]
Still doesn't work. I get the same exact error.

**Comment by JoseMendesGouveia** [comment]
Double check the structure and values of your queryString and URL path.

**Comment by backofthecup** [comment]
Again, you have the code above: Why does it work on 2.0.0.alpha1 but not on 2.0.0.beta1?

I modified the code accordingly:
````
NSArray *keys = [NSArray arrayWithObjects:@"authToken", @"apiKey", nil];
NSArray *values = [NSArray arrayWithObjects:authToken, CCAPIKey, nil];
NSDictionary *params = [[NSDictionary alloc] initWithObjects:values forKeys:keys];
````

**Comment by backofthecup** [comment]
@joeldart 
Do you have anything to add here?

**Comment by joeldart** [comment]
https://github.com/DyKnow/SignalR-ObjC/issues/198#issuecomment-127296776 is being handled in #190 so I think there is nothing new in this issue
