### ISSUE TITLE
Xcode 6.4: ld: library not found for -lSignalR.Client.iOS

### ISSUE THREAD

**Issue by nikunjsilicon** [DyKnow/SignalR-ObjC#204]
Hi DyKnow,

Hope you are doing good.
I have download the source code and install latest cocoa pods of SignalR-Objc but not compile the project and also checked "$(inherited)" under Other Linker Flags in Target Build Settings so can you please help me to resolve the issue. 

Compile error: ld: library not found for -lSignalR.Client.iOS

Thanks
Nikunj Jadav

**Comment by joeldart** [comment]
if you delete your Pods directory and run ```pod install``` what's the output?

**Comment by nikunjsilicon** [comment]
Hi Joeldart,
Thanks for reply.
Ok no issue. I am create new demo and install new cocoa pods SignalR-Objc Library and its working.
I have facing one issue to send text message to server after successfully connection with server.
I am getting connectionToken and connectionId after successfully connect to server but can't send message to server.
I am developing chat application between operator to customer.
Download source code from github and checked studied ChatController.m file so I think its a controller to chat between two users, correct? If no, please let me know the controller class where all code works like send text message, receive message, disconnect etc.
For connection, I have used below code.
============================================
NSString *server = [Router sharedRouter].server_url;
    connection = [SRHubConnection connectionWithURLString:server];
    hub = [connection createHubProxy:@"chatHub"];
    
    [[hub state] setValue:@YES forKey:@"focus"];
    [[hub state] setValue:0 forKey:@"unread"];
    
    [hub on:@"refreshRoom" perform:self selector:@selector(refreshRoom:)];
    [hub on:@"showRooms" perform:self selector:@selector(showRooms:)];
    [hub on:@"addMessageContent" perform:self selector:@selector(addMessageContent:content:)];
    [hub on:@"addMessage" perform:self selector:@selector(addMessage:name:message:)];
    [hub on:@"addUser" perform:self selector:@selector(addUser:exists:)];
    [hub on:@"changeUserName" perform:self selector:@selector(changeUserName:newUser:)];
    [hub on:@"sendPrivateMessage" perform:self selector:@selector(sendPrivateMessage:to:message:)];
    [hub on:@"sendMeMessage" perform:self selector:@selector(sendMeMessage:message:)];
    [hub on:@"leave" perform:self selector:@selector(leave:)];

    [connection setDelegate:self];
    [connection start];
==========================
Errors: [SRWebSocketTransport webSocket:didReceiveMessage:] 
[WEB_SOCKETS]    WS Receive: {"I":"0","E":"There was an error invoking Hub method 'chatHub.Join'."}
{"I":"1","E":"There was an error invoking Hub method 'chatHub.Send'."}

so please help me for resolve my issue. Hope I can get help from your side so that will be appreciate to you from my side.

Thanks
Nikunj Jadav

**Comment by nikunjsilicon** [comment]
Hi Joeldart,

Please see open this link and help me to solve out the issue. 
https://github.com/DyKnow/SignalR-ObjC/issues/208

Thanks 
Nikunj Jadav
