### ISSUE TITLE
There was an error invoking Hub method 'chatHub.Join

### ISSUE THREAD

**Issue by nikunjsilicon** [DyKnow/SignalR-ObjC#208]
Hi Joeldart,
I am create new demo and install new cocoa pods SignalR-Objc Library and its working.
I have facing one issue to send text message to server after successfully connection with server.
I am getting connectionToken and connectionId after successfully connect to server but can't send message to server.
I am developing chat application between operator to customer.
Download source code from github and checked studied ChatController.m file so I think its a controller to chat between two users, correct? If no, please let me know the controller class where all code works like send text message, receive message, disconnect etc.

For connection, I have used below code.
============================================
NSString *server = [Router sharedRouter].server_url;
    connection = [SRHubConnection connectionWithURLString:server];
    hub = [connection createHubProxy:@"chatHub"];
    
    [[hub state] setValue:@YES forKey:@"focus"];
    [[hub state] setValue:0 forKey:@"unread"];
    
    [hub on:@"refreshRoom" perform:self selector:@selector(refreshRoom:)];
    [hub on:@"showRooms" perform:self selector:@selector(showRooms:)];
    [hub on:@"addMessageContent" perform:self selector:@selector(addMessageContent:content:)];
    [hub on:@"addMessage" perform:self selector:@selector(addMessage:name:message:)];
    [hub on:@"addUser" perform:self selector:@selector(addUser:exists:)];
    [hub on:@"changeUserName" perform:self selector:@selector(changeUserName:newUser:)];
    [hub on:@"sendPrivateMessage" perform:self selector:@selector(sendPrivateMessage:to:message:)];
    [hub on:@"sendMeMessage" perform:self selector:@selector(sendMeMessage:message:)];
    [hub on:@"leave" perform:self selector:@selector(leave:)];

    [connection setDelegate:self];
    [connection start];
==========================
Errors: [SRWebSocketTransport webSocket:didReceiveMessage:] 
[WEB_SOCKETS]    WS Receive: {"I":"0","E":"There was an error invoking Hub method 'chatHub.Join'."}
{"I":"1","E":"There was an error invoking Hub method 'chatHub.Send'."}

so please help me for resolve my issue. Hope I can get help from your side so that will be appreciate to you from my side.

Thanks
Nikunj Jadav

**Comment by joeldart** [comment]
Off hand I only use server-push functionality so it will take me a little
time to get this setup. Any of the other users using client -> server hub
able to see what is being done incorrectly?

**Comment by abillingsley** [comment]
@nikunjsilicon can you please provide a code snippet of the server code you are using on the ChatHub.cs also in your code snippet above I do not see where you are attempting to send a message to ChatHub can you please share that as well.

**Comment by nikunjsilicon** [comment]
Hi abillingsley and joeldart, 

Thanks for reply, I have found the issue that there is not any method on server side and successfully chat communication between app to web and send and receive message.

There are different methods on server side so I have integrate it and its working fine for me.

Thanks 
Nikunj Jadav
