### ISSUE TITLE
Error (-[__NSGlobalBlock__ localizedFailureReason]: unrecognized selector sent to instance 0x100347490) on SRHubConnection stop

### ISSUE THREAD

**Issue by neira24** [DyKnow/SignalR-ObjC#209]
When i am trying to stop the connection  it throws this error -[__NSGlobalBlock__ localizedFailureReason]: unrecognized selector sent to instance 0x100347490. I am using SignalR-ObjC', '~> 2.0.0.beta1
SocketRocket', '~> 0.3.1-beta2
Any ideas how to fix this problem or where to start. 

Thanks!

**Comment by joeldart** [comment]
unrecognized selector usually means the object is not the expected type, in my experience. Set a breakpoint for thrown exceptions and see if you can see what method it's trying to call.

**Comment by neira24** [comment]
The problem  was in this error block. I used [error localizedDescription] instead of error and it gave me the  -[NSGlobalBlock localizedFailureReason]: .... error. But the stop 

 hubConnection.error=^(NSError *error){
            
      
            NSLog(@"Error: %@",error);
            
         
        };

But on stop it now gives me exe_bad_access in SRWebSocket.m file in (void)_failWithError:(NSError *)error; method in the [self.delegate respondsToSelector:@selector(webSocket:didFailWithError:)] . The stop seems to start reconnecting the connection instead of stopping it, and after lots of reconnecting attempts it crashes with the exc_bad_access(code=EXC_I386_GPFLT).
