### ISSUE TITLE
Experiencing crashing issues with beta1

### ISSUE THREAD

**Issue by tumatauenga** [DyKnow/SignalR-ObjC#213]
Hi there, 

I just thought I'd let you know I have had a number of crashing issues with the beta1 branch.

1. Despite the fact that [it appears that `SRWebSocketTransport` is appropriately setting itself as the delegate of the `SRWebsocket` here][1], I periodically get a crash at [this line][2], where it appears the delegate is now an `NSDictionary` instead of the `SRWebSocketTransport`, and since an `NSDictionary` doesn't respond to a selector of the form `webSocket:didReceiveMessage:` I get a crash. This is not consistently reproducible, it only happens every now and then.

2. Sometimes I get a crash on [a particular line in SRLongPollingTransport][3], where for some reason the `connectionToken` is null, and since an NSDictionary is being created with a null object, we get a crash.

For these reasons I'm going to revert back to the alpha1 tag for the time being, which seems much more stable.

[1]: https://github.com/DyKnow/SignalR-ObjC/blob/abc26be2d9d97edfdf8856fd9e27367fab38b27c/SignalR.Client/Transports/SRWebSocketTransport.m#L121
[2]: https://github.com/square/SocketRocket/blob/f61e3c3ae532bf72f0c75524c92e95d625283a13/SocketRocket/SRWebSocket.m#L753
[3]: https://github.com/DyKnow/SignalR-ObjC/blob/abc26be2d9d97edfdf8856fd9e27367fab38b27c/SignalR.Client/Transports/SRLongPollingTransport.m#L102

**Comment by abillingsley** [comment]
@tumatauenga we are in the process of adding test coverage and handling several error states in the transports.  You can find this progress on the feature-198 branch.  

1. Seems to be resolved by bumping the version of SocketRocket.  SocketRocket was not maintaining a weak reference to the delegate
2. Should be resolved by https://github.com/DyKnow/SignalR-ObjC/commit/8af9694bc0f70b8540eb64e72325a682b8e18420 

Please let us know if you have more success with feature-198

**Comment by tumatauenga** [comment]
Thanks @abillingsley, I'm now on the beta3 branch, we're in regression for the next couple of weeks so I'll let you know how it goes.
