### ISSUE TITLE
Malloc Error

### ISSUE THREAD

**Issue by JoseMendesGouveia** [DyKnow/SignalR-ObjC#216]
During app testing I had the same error that crashes my app. The error occurred several times in random situations.

Error: malloc: *** error for object 0x7a19f204 incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

The error lies on SREventSourceStreamReader.m class, in the line 92:
 NSData *buffer = [stream propertyForKey: NSStreamDataWrittenToMemoryStreamKey];

Does this error happened to someone else?

**Comment by joeldart** [comment]
Are you on beta3 in your testing? We've added a ton more unit tests and handling of edge cases. Also, could you add some more context to "random situations" like what's your workload, server version, etc?

**Comment by JoseMendesGouveia** [comment]
Hi Joel,

Thanks for your reply.
No, I'm not on beta3, I'm using the master release from mid August.
The SignalR server version is 2.0 with a IIS7.5.
The workload from the server is normal and without any visible load variation, the error occurs, that's why I mention "random situations". I can't find any plausable reason or have any hint about its cause.
I cannot replicate the issue, although I'm trying to.

**Comment by joeldart** [comment]
@JoseMendesGouveia I would suggest bumping to beta3. It is the most stable version and handles state transitions much better across all the various transports

**Comment by JoseMendesGouveia** [comment]
Thank you Joel, I will try beta3 and give feedback as soon as possible.

**Comment by JoseMendesGouveia** [comment]
Hello Joel,

I have been testing beta3 version for some time now, and so far so good, I didn't had any malloc error yet. Thanks.

**Comment by DanMorganiOS** [comment]
Hi everyone,

Sorry to bring this back up, but I'm having the same issue occasionally.  I'm on a staging build where the hub I'm connecting to sends content every second - so a very high traffic scenario.

**Comment by joeldart** [comment]
@DanMorganiOS this particular message can be pretty generic. could you open a new issue with the message/stack trace, version you're running, and what you are doing to reproduce the issue?
