### ISSUE TITLE
Compiler issues

### ISSUE THREAD

**Issue by eak65** [DyKnow/SignalR-ObjC#217]
I am using IOS 9. When I did pod 'SignalR-Objc', then pod install, it seems to download. When I opened up the workspace, I have compiler issues.

It says it installed
"Installing SignalR-ObjC (1.0.1)"

is that correct?

**Comment by flotteur** [comment]
Try changing your podfile config to something like:

 pod 'SignalR-ObjC', '~> 2.0.0.beta'
