### ISSUE TITLE
How to get connnection state? 

### ISSUE THREAD

**Issue by MakerXia** [DyKnow/SignalR-ObjC#223]
How to get connnection state?   connection.active? Thank you!

**Comment by sallyahmed** [comment]
from 
SRConnectionDelegate 

- (void)SRConnectionDidOpen:(id <SRConnectionInterface>)connection;

- (void)SRConnectionWillReconnect:(id <SRConnectionInterface>)connection;

- (void)SRConnectionDidReconnect:(id <SRConnectionInterface>)connection;

- (void)SRConnection:(id <SRConnectionInterface>)connection didReceiveData:(id)data;

- (void)SRConnectionDidClose:(id <SRConnectionInterface>)connection;

- (void)SRConnection:(id <SRConnectionInterface>)connection didReceiveError:(NSError *)error;

- (void)SRConnection:(id <SRConnectionInterface>)connection didChangeState:(connectionState)oldState newState:(connectionState)newState;

- (void)SRConnectionDidSlow:(id <SRConnectionInterface>)connection;

**Comment by MakerXia** [comment]
3Q

**Comment by abillingsley** [comment]
connection.connectionState, one of the delegate methods or the various block callbacks can all be used to gain insight into the connection state
