### ISSUE TITLE
Invalid version

### ISSUE THREAD

**Issue by aexmachina** [DyKnow/SignalR-ObjC#224]
When I try to submit my app to iTunes Connect I get the following error `This bundle is invalid. The value for key CFBundleShortVersionString '2.0.0.beta3' in the Info.plist file must be a period-separated list of at most three non-negative integers.` If I manually change this value in `build.xcarchive/dSYMs/SignalR_ObjC.framework.dSYM/Contents/Info.plist` then the error does not happen.

**Comment by tumatauenga** [comment]
Having this issue as well. Hopefully we'll get a 2.0.0 non-beta release soon.

**Comment by abillingsley** [comment]
please see version 2.0.1 now on cocoapods
