### ISSUE TITLE
Connection ID is in the wrong format iOS ? (Websockets)

### ISSUE THREAD

**Issue by ohnomycoco** [DyKnow/SignalR-ObjC#227]
I am getting this error when trying to connect to a websocket server using the framework. Is this project still working with iOS9 ?

**Comment by mqh-mm** [comment]
The file---README is too old.Could you please provide someting new? I am a novice, I want the right guidance.

**Comment by mqh-mm** [comment]
@ohnomycoco

**Comment by abillingsley** [comment]
iOS 9 is supported
