### ISSUE TITLE
Error with use_frameworks! CocoaPods flag

### ISSUE THREAD

**Issue by tumatauenga** [DyKnow/SignalR-ObjC#238]
When using the `use_frameworks!` CocoaPods flag with the 2.0.1 version of the SignalR-ObjC library, I get the following errors:

`Include of non-modular header inside framework module 'SignalR_ObjC.SREventSourceRequestSerializer'`

`Include of non-modular header inside framework module 'SignalR_ObjC.SREventSourceResponseSerializer'`

This is caused by the two `#import` statements that import the `AFNetworking` base classes. Instead of being written like this:

```
#import "AFURLRequestSerialization.h"
#import "AFURLResponseSerialization.h"
```

They should be written like this:

```
#import <AFNetworking/AFURLRequestSerialization.h>
#import <AFNetworking/AFURLResponseSerialization.h>
```

**Comment by abillingsley** [comment]
thanks for the pull request.  merged
