### ISSUE TITLE
Use SignaR-ObjC in swift class

### ISSUE THREAD

**Issue by pampua84** [DyKnow/SignalR-ObjC#240]
Hi guys,
i tried to use SignalR-ObjC in my swift class after i install cocoapods, install podfile. It's all ok.
I created a bridging file to use this library(framework) in my Swift project. I write the following code:
      
      import UIKit
      import SignalR_ObjC

     class ViewController: UIViewController, SRConnectionDelegate {
    
    
    @IBOutlet weak var btn_Login: UIButton!
    
    var hubConnection = SRHubConnection(URLString: "http://myUrl.com");
    
    var hubProxy = SRHubProxy();

    override func viewDidLoad() {

        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    

   @IBAction func btn_Login(sender: AnyObject) {

        hubProxy = SRHubProxy(connection: hubConnection, hubName: "MyHub");
    
        let signInSelector = Selector("signInResponse:");
    
        hubProxy.on("signIn", perform: self, selector: signInSelector);
       
        hubConnection.delegate = self;

        hubConnection.start();
        
        self.SRConnectionDidOpen(hubConnection);

    }

    func SRConnectionDidOpen(connection: SRConnectionInterface!) {
        
        hubProxy.invoke("SignIn", withArgs: ["test","apple"])
   
    }

    func signInResponse(response: String) {      
        NSLog(response);
  }

The connection starts and the invoke is ok, they work fine, but i don't receive answer, the hubProxy.on is never called. Can anyone Help me Please??

Thank You 
Fra

**Comment by gunesmert** [comment]
Hey pampua84, can you tell me how did you integrate it to Swift project. I am having problems building my project after I updated to version 2.0.1

**Comment by pampua84** [comment]
Hi Gunes, i have created a podFile like this:

    platform :ios, '9.0'
    use_frameworks!
    pod 'AFNetworking', '2.6.3'
    pod 'SocketRocket', '0.3.1-beta2'
    pod 'SignalR-ObjC', '2.0.0.beta1'

and then i create a Bridging_Header where import SignalR.H. 
I hope to be helpful

**Comment by gunesmert** [comment]
Hi pampua84,

Thx for your answer. The problem was because of Cocoapods version. I was using 1.0.0.beta.3 and downgrading Cocoapods to 0.39.0 solved my problem.

**Comment by jbcaveman** [comment]
FYI, for anyone wanting to use this Obj-C library in their Swift project: You might not be able to receive messages from your server under certain conditions. I don't know the conditions, but the proxy won't get the message and your connection delegate won't fire "didReceiveData" either. I was experiencing this, but when I ran an Objective-C implementation with the exact same configuration, everything worked great. Something here doesn't play nice with Swift.

**Comment by ergunkocak** [comment]
There is also a swift port : https://github.com/skerkewitz/SwignalR
