### ISSUE TITLE
Build Swift project with SignalR

### ISSUE THREAD

**Issue by gunesmert** [DyKnow/SignalR-ObjC#241]
I was using version 2.0.0.beta3 and today I realized version 2.0.1 is up and updated my Podfile.

Right now, I am able to import SignalR-ObjC, but can not build the project with it.

Is there anyone, who integrated version 2.0.1 succesfully to a Swift project?

**Comment by tumatauenga** [comment]
Yes I was able to successfully integrate. Can you give some more information about the errors you are seeing?

**Comment by gunesmert** [comment]
I was using SignalR-ObjC version 2.0.0.beta3 with Cocoapods version 1.0.0.beta.3

Everything was working fine until I decided to upgrade SignalR-ObjC to version 2.0.1

I executed pod update, everything gets successfully updated but when I hit Build on my Xcode project, I am getting "Could not build Objective-C module 'SignalR-ObjC'" error on line import SignalR-ObjC

**Comment by tumatauenga** [comment]
I'm not using the 1.0.0.beta.3 version of CocoaPods, I'm still on 0.39.0, but I had a problem where a couple of classes in the SignalR-ObjC Library weren't importing the AFNetworking framework correctly when using the `use_frameworks!` flag. I fixed it by changing the import statement in these two classes 

'
SREventSourceRequestSerializer.h
SREventSourceResponseSerializer.h
'

to:

`
@import AFNetworking;
`

Hope that helps.

**Comment by gunesmert** [comment]
Downgrading to Cocoapods version 0.39.0 and making those import changes allowed me to build the project. Thx mate

**Comment by ergunkocak** [comment]
There is also a swift port : https://github.com/skerkewitz/SwignalR
