### ISSUE TITLE
How to close log in version 2.01

### ISSUE THREAD

**Issue by MakerXia** [DyKnow/SignalR-ObjC#242]
Thank you

**Comment by MakerXia** [comment]
Close print log in console,3Q

**Comment by MakerXia** [comment]
who can help me?

**Comment by abillingsley** [comment]
Unless you are using Cocoalumberjack for logging there is no publicly exposed api to support this at this time.

If you cannot use Cocoalumberjack to control your logs and are willing to modify the SignalR-ObjC source in either a Fork or locally please take a look at [SRLog.h](https://github.com/DyKnow/SignalR-ObjC/blob/master/SignalR.Client/SRLog.h#L41)

You will notice that the following Log Macros when cocoalumberjack is not used simply perform an NSLog

```
#define SRLogError(frmt, ...)      do{ NSLog((frmt), ##__VA_ARGS__); } while(0)
#define SRLogWarn(frmt, ...)       do{ NSLog((frmt), ##__VA_ARGS__); } while(0)
#define SRLogInfo(frmt, ...)       do{ NSLog((frmt), ##__VA_ARGS__); } while(0)
#define SRLogDebug(frmt, ...)      do{ NSLog((frmt), ##__VA_ARGS__); } while(0)
#define SRLogVerbose(frmt, ...)    do{ NSLog((frmt), ##__VA_ARGS__); } while(0)
```

If you were to change this to nOOp or were to protect NSLog by some condition you can control when or if logging occurs.  

If you end up making changes and would like to provide a patch for our consideration please send us a pull request with your changes for review
