### ISSUE TITLE
Compile fails with: Include of non-modular header inside framework module 'SignalR_ObjC.SREventSourceRequestSerializer'

### ISSUE THREAD

**Issue by aminbagheri** [DyKnow/SignalR-ObjC#252]
### Description

Having a compile problem with Swift project that uses SignalR-ObjC + having frameworks enabled (use_frameworks! in Podfile) in CocoaPods:

.../tempproj/Pods/SignalR-ObjC/SignalR.Client/Transports/ServerSentEvents/SREventSourceRequestSerializer.h:23:9: Include of non-modular header inside framework module 'SignalR_ObjC.SREventSourceRequestSerializer'

in SREventSourceRequestSerializer.h, changing 
  #import "AFURLRequestSerialization.h"
to
  #import "AFNetworking/AFNetworking-umbrella.h"
fixes the issue.

(same for SREventSourceResponseSerializer.h)

the proper change could be:

#if __has_include(<AFNetworking/AFNetworking-umbrella.h>)
  #import <AFNetworking/AFNetworking-umbrella.h>
#else
  #import <AFURLResponseSerialization.h>
#endif

### Replication Steps
1. have a Podfile as below:

use_frameworks!
pod 'Bond', '4.1.1'
pod 'SignalR-ObjC', '2.0.1'

2. "import SignalR_ObjC" in a Swift files in project.
3. Compile -> fails

### Server Version
> Which version of SignalR Server are you using

N/A

### Client Version
> Which version(s) of SignalR-ObjC does the behavior occur on (you can see this in the Podfile.lock if using Cocoapods)

2.0.1

##### Dependency Versions
> Which version(s) of SignalR-ObjC's dependencies are in use when the behavior occurs (you can see this in the Podfile.lock if using Cocoapods)

* AFNetworking: 2.6.3
* SocketRocket: 0.4.2

### Environments Impacted
 - [ ] iOS 
     - [ ] 7.0
     - [ ] 8.0
     - [x] 9.0
 - [ ] OSX 
    - [ ] 10.9 (Mavericks)
    - [ ] 10.10 (Yosemite)
    - [ ] 10.11 (El Capitan)

### Testing

**Test Cases**
 - [ ] General replication steps

**Edge Cases**
 - [ ] Unique cases outside of replication steps

**Comment by abillingsley** [comment]
the version as it exists on CocoaPods does not support use_frameworks this has been resolved in https://github.com/DyKnow/SignalR-ObjC/commit/26b8302e79d6b7d983d3d03620cdf37960bd477b and will be made available in 2.0.2
