### ISSUE TITLE
Issue in invoke event

### ISSUE THREAD

**Issue by chassrouny** [DyKnow/SignalR-ObjC#259]
Hello,

I subscribed for a custom event using 
`
SRHubProxy *chat = [connection createHubProxy:@"ChatHub"];
`
`
 [chat on:@"MessageReceived" perform:self selector:@selector(MessageReceived:messageId:message:senderId:)];
`
but i am getting method signature argument cannot be nil exception
 I attached an image
<img width="1095" alt="screen shot 2016-04-11 at 3 53 13 pm" src="https://cloud.githubusercontent.com/assets/9074156/14427579/2834c49e-fffe-11e5-9bb0-70df774aa4cf.png">

Thanks in advance

**Comment by abillingsley** [comment]
According to the [documentation](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/#//apple_ref/occ/instm/NSObject/methodSignatureForSelector:) the signature will be nil under the following condition

> An NSMethodSignature object that contains a description of the method identified by aSelector, or **nil if the method can’t be found.**

My best guess is the selector `@selector(MessageReceived:messageId:message:senderId:)` does not exist on the object `self`.  Maybe you have a typo?

**Comment by charbelhass** [comment]
thanks @abillingsley 😄

**Comment by chassrouny** [comment]
thanks @abillingsley 😄
