### ISSUE TITLE
I have two issues 1.SRLongPollingTransport is not updated with AFNetworking 3.0*  Issue 2. Not compiling the framework in static library

### ISSUE THREAD

**Issue by NarayanaT** [DyKnow/SignalR-ObjC#265]
**ISSUE 1**. I have downloaded the source code, and I want use it for my custom iOS App, 
So I have copied the "NetWork" & "SignalR.Client"  folders.
Now I have installed AFNetworking and SocketRocket through Pods.
It seems the AFNetWork is updated to version 3.\* where as the SRLongPollingTransport is not updated.

**ISSUE2:**  I have downloaded the source code, and I want use it for my custom iOS App, 
So I have copied the "NetWork" & "SignalR.Client"  folders.
Now I have installed AFNetworking to 2.6.3 version and SocketRocket through Pods.
I want to develope a library file which including the WebSocket, that means the SignalR code is inside of my library where as the library I have to use in another project.
It's building properly and generating the library (.a) file.

Now, when I add the library in to another new project then it's not compiling, it's throwing some errors saying 
a.   Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SRWebSocket", referenced from:", 

Some times it says armv64, or linker errors 
 b. Undefined symbols for architecture arm64:
  "_utf8_nextCharSafeBody", referenced from:
      _validate_dispatch_data_partial_string in xxxxxxxxxx.a(SRWebSocket.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
## Finally I have blocked in the above two ways. Please help me to build the SocketRocket framework in my library.

Thanks in Advance
Narayana

**Comment by joeldart** [comment]
Issue 1: We don't currently have signalr-objc working against AFNetworking 3. 
Issue 2: I'm not sure I understand what you're trying to do. Why not install using cocoapods as in https://github.com/DyKnow/SignalR-ObjC/blob/feature-dev/README.md

**Comment by NarayanaT** [comment]
@joeldart  Thanks for the reply,
Now I have integrated 
 'AFNetworking', '2.6.3'
 'SocketRocket', '0.4.2' via pods in my StaticLibrary project (libOne.a is product for that), now I have added the "libOne.a" file into another project, and try build, Im getting linker errors like 

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SRWebSocket", referenced from:
      objc-class-ref in libOne.a(One.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Can you please guide me to resolve it

**Comment by abillingsley** [comment]
Based on the new error chances are there is an error in the "Other Linker Flags" build setting for the target that you are integrating libOne into.

Is there a reason you are integrating into a Static Lib and then integrating that Static Lib into your app target?  You might be able to simplify things a bit by just integrating SignalR-ObjC into your app target directly.  

What you are trying to do can be accomplished but is not the happy path that cocoapods strives to support so you are going to fight against the tooling a little bit.
