### ISSUE TITLE
useDefault parameter in SRHubConnection.initWithURLString:useDefault: got replaced

### ISSUE THREAD

**Issue by bull-xu** [DyKnow/SignalR-ObjC#266]
In SRHubConnection.m

Line 51 to instant the hub connection by passing NO to useDefault:
`- (instancetype)initWithURLString:(NSString *)URL useDefault:(BOOL)useDefault`

Line 52 calls super.initWithURLString without useDefault parameter, and the super class will call 
`- (instancetype)initWithURLString:(NSString *)url queryString:(NSDictionary *)queryString`
(to Line 58)

On line 59, the useDefault sets to YES, will cause the URL string wrong.

**Comment by abillingsley** [comment]
duplicate of #165
